version: '3'
services:
  # Application Dockerfile is in same folder which is .
  db:
    build:
      context: ./db
    ports:
      - "33060:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy

