name: Hello World App Workflow
on:
  push:
    branches:
      - master
      - lab08

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Remove existing test_db directory (if any)
        run: |
          rm -rf db/test_db

      - name: Download external test_db
        run: |
          git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build Database Docker Image
        run: |
          docker build -t database ./db

      - name: Run Database Docker Container
        run: |
          docker run --name employees -dp 33060:3306 database

      - name: Run Integration Tests
        run: |
          mvn -Dtest=com.napier.sem.AppIntegrationTest test

      - name: Stop and Remove Docker Container
        run: |
          docker stop employees
          docker rm employees

      - name: Remove Docker Image
        run: |
          docker image rm database

  Build:
    name: Build and Start Using Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Package and Run Docker Compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
