name: Build and Test Hello World App

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Run docker compose
        run: docker compose up --build --abort-on-container-exit

      - name: Shutdown docker compose
        if: always()
        run: docker compose down
