name: Hello World App Workflow
on:
  push:
    branches:
      - master
      - develop

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Download external test_db
        run: git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          flags: UnitTests
          verbose: true

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Download external test_db
        run: git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Integration Tests
        run: |
          docker build -t database ./db
          docker run --name employees -v ${{ github.workspace }}/db/init.sql:/docker-entrypoint-initdb.d/init.sql -e MYSQL_ROOT_PASSWORD=example -dp 33060:3306 database
          mvn -Dtest=com.napier.sem.AppIntegrationTest verify
          docker stop employees
          docker rm employees
          docker image rm database

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          flags: IntegrationTests
          verbose: true

  BuildAndRelease:
    name: Build, Start docker-compose, Deploy Release, and Copy Reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Download external test_db
        run: git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Package and Run docker-compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

      - name: Copy Output Reports from Docker Container
        run: |
          # Get the container ID of the running container
          CONTAINER_ID=$(docker ps -aqf "name=employees")
          echo "Copying reports from container $CONTAINER_ID"
          docker cp $CONTAINER_ID:/app/reports ./reports


      - name: Deploy Reports to GitHub Branch
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports    # Branch to deploy reports to
          folder: reports    # Folder to deploy

      - name: Deploy JAR to GitHub Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}  # Use your PAT here
          prerelease: false
          automatic_release_tag: latest        # This overwrites the "latest" release
          files: |
            ./target/*.jar
