name: Hello World App Workflow
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Download external test_db
        run: |
          git clone --depth 1 https://github.com/datacharmer/test_db.git db/test_db

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

  Build:
    name: Build and Start Using docker-compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Package and Run docker-compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
